# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = ""
  url = ""
  weight = 1
  pre = "<img src='/img/utd.png' style='height: 40px; width: 40px;' alt='UTD Logo'>"

[[main]]
  name = "Home"
  url = "#about"
  weight = 10
  pre = "<i class='fas fa-terminal'>&nbsp;</i>"

[[main]]
  name = "Research"
  url = "#publications"
  weight = 40
  
 [[main]]
  name = "Talks"
  url = "#talks"
  weight = 50
  
 [[main]]
 name = "Teaching"
 url = "#teaching"
 weight = 60

 [[main]]
  name = "Connect"
  url = "#contact"
  weight = 130

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
